# **Statsmodels**




<img src= 'https://www.statsmodels.org/stable/_images/statsmodels-logo-v2-horizontal.svg' width=500/>

- `Statsmodels` is a Python library that provides classes and functions for the estimation of many different statistical models.

- Statsmodels provides many statistical models, the most basics are linear regression and logistic regression. Depending on your needs you can check statsmodels library from [here](https://www.statsmodels.org/stable/index.html), and see if the model you are looking exist in Statsmodels.

- There is another great package called scikit-learn that also provides statistical tools like regressions. See its offical website [here](https://scikit-learn.org/stable/). People who work in machine learning business use Scikit-learn a lot.

# Load libraries and data

In [1]:
import numpy as np
import pandas as pd

import statsmodels.api as sm

we will use a data from stata's data repository. It is about cars. It has some information about cars that we can play aroud.

In [2]:

# getting a data from Stata
df=sm.datasets.webuse('auto')

df.head()

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic

In [3]:
df.columns

Index(['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'foreign'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74 entries, 0 to 73
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   make          74 non-null     object
 1   price         74 non-null     int16
 2   mpg           74 non-null     int16
 3   rep78         69 non-null     float64
 4   headroom      74 non-null     float32
 5   trunk         74 non-null     int16
 6   weight        74 non-null     int16
 7   length        74 non-null     int16
 8   turn          74 non-null     int16
 9   displacement  74 non-null     int16
 10  gear_ratio    74 non-null     float32
 11  foreign       74 non-null     category
dtypes: category(1), float32(2), float64(1), int16(7), object(1)
memory usage: 3.5+ KB

In [5]:
df.shape

(74, 12)

In [6]:
df.describe()

,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio
count,74.000000,74.000000,69.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,6165.256757,21.297297,3.405797,2.993243,13.756757,3019.459459,187.932432,39.648649,197.297297,3.014865
std,2949.495885,5.785503,0.989932,0.845995,4.277404,777.193567,22.266340,4.399354,91.837219,0.456287
min,3291.000000,12.000000,1.000000,1.500000,5.000000,1760.000000,142.000000,31.000000,79.000000,2.190000
25%,4220.250000,18.000000,3.000000,2.500000,10.250000,2250.000000,170.000000,36.000000,119.000000,2.730000
50%,5006.500000,20.000000,3.000000,3.000000,14.000000,3190.000000,192.500000,40.000000,196.000000,2.955000
75%,6332.250000,24.750000,4.000000,3.500000,16.750000,3600.000000,203.750000,43.000000,245.250000,3.352500
max,15906.000000,41.000000,5.000000,5.000000,23.000000,4840.000000,233.000000,51.000000,425.000000,3.890000

# Basic correlation

Let's do a basic correlation using `SciPy`.

In [7]:
from scipy.stats import pearsonr

# Sample data for two variables
var1 = df['price']
var2 = df['mpg']

# Compute correlation coefficient and p-value
correlation_coefficient, p_value = pearsonr(var1, var2)

print("Correlation Coefficient:", correlation_coefficient)
print("P-value:", "{:7f}".format(p_value))
print("P-value:", p_value)

Correlation Coefficient: -0.468596688195187
P-value: 0.000025
P-value: 2.546131205143075e-05

# Simple Linear Regression

$$ y= β_{0} + β{_1}×x_1 + ϵ$$

**$y$**= Dependent variable

**$β_{0}$**= Constant

$β{_1}$= Coefficent

$x_1$= Independent Variable

$ϵ$ = error/unexplained

Lets remember the car data we have

In [8]:
df.head()

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic

## Building simple regression model

let's say this is our hypothesis:

**H:** The pricier the car is, the more likely it will consume a lot of gas.

So we use linear regression when we have a continious dependent variable not binary variables.

In this case,

Our dependent variable (the things we want to explain) is the gas consumption, `mpg`

Our independent variable is `price` of cars.

Lets build our simple linear regression

In [9]:
#remember the regression formula above
# y is dependent variable
# x is independent variable

y=df['mpg']
x= df['price']

In [10]:
y

0     22
1     17
2     22
3     20
4     15
      ..
69    23
70    41
71    25
72    25
73    17
Name: mpg, Length: 74, dtype: int16

In [11]:
x

0      4099
1      4749
2      3799
3      4816
4      7827
      ...
69     7140
70     5397
71     4697
72     6850
73    11995
Name: price, Length: 74, dtype: int16

In [12]:
#so our b0 is technically b0*1 but it is not stated as is.
# if we want to have constant to be presented in our model, then we have to add it.
#here is how to do

x1=sm.add_constant(x)

x1

    const  price
0     1.0   4099
1     1.0   4749
2     1.0   3799
3     1.0   4816
4     1.0   7827
..    ...    ...
69    1.0   7140
70    1.0   5397
71    1.0   4697
72    1.0   6850
73    1.0  11995

[74 rows x 2 columns]

## Now, we are ready to fit the model

In [13]:
model= sm.OLS(y, x1).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.220
Model:                            OLS   Adj. R-squared:                  0.209
Method:                 Least Squares   F-statistic:                     20.26
Date:                Sat, 29 Jul 2023   Prob (F-statistic):           2.55e-05
Time:                        22:36:54   Log-Likelihood:                -225.22
No. Observations:                  74   AIC:                             454.4
Df Residuals:                      72   BIC:                             459.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         26.9642      1.394     19.344      0.000      24.185      29.743
price         -0.0009      0.000     -4.501      0.000      -0.001      -0.001
==============================================================================
Omnibus:                       18.925   Durbin-Watson:                   1.479
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.916
Skew:                           1.159   Prob(JB):                     6.41e-06
Kurtosis:                       4.544   Cond. No.                     1.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

So considering only price as our independent variable, it can be seen that unit increase in price of a car decreases mpg by 0.0009 in a car. The result is statistically significant.

That is expected because people who pay more for cars look for luxurious features in car. So very luxurious cars consume a lot of gas due to their engine etc.

# Multiple linear regression

When you have more than one independent variable. Or when you want to control for other important variables that may affect say `mpg` then we have to add additional variable into our model.

So the new formula is:

$$ y= β_{0} + β{_1}×x_1 + β{_2}×x_2 + ⋯ + β{_k}×x_k + ϵ$$

## Building the model

lets say that `weight` of car also affect how much the car will consume in addition to `price`.

In [14]:
y=df['mpg']
x= df[['price', 'weight']]

In [15]:
y

0     22
1     17
2     22
3     20
4     15
      ..
69    23
70    41
71    25
72    25
73    17
Name: mpg, Length: 74, dtype: int16

In [16]:
x

    price  weight
0    4099    2930
1    4749    3350
2    3799    2640
3    4816    3250
4    7827    4080
..    ...     ...
69   7140    2160
70   5397    2040
71   4697    1930
72   6850    1990
73  11995    3170

[74 rows x 2 columns]

In [17]:
x1=sm.add_constant(x)

x1

    const  price  weight
0     1.0   4099    2930
1     1.0   4749    3350
2     1.0   3799    2640
3     1.0   4816    3250
4     1.0   7827    4080
..    ...    ...     ...
69    1.0   7140    2160
70    1.0   5397    2040
71    1.0   4697    1930
72    1.0   6850    1990
73    1.0  11995    3170

[74 rows x 3 columns]

In [18]:
model= sm.OLS(y, x1).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     66.85
Date:                Sat, 29 Jul 2023   Prob (F-statistic):           4.73e-17
Time:                        22:36:54   Log-Likelihood:                -195.22
No. Observations:                  74   AIC:                             396.4
Df Residuals:                      71   BIC:                             403.3
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         39.4397      1.622     24.322      0.000      36.206      42.673
price      -9.351e-05      0.000     -0.575      0.567      -0.000       0.000
weight        -0.0058      0.001     -9.421      0.000      -0.007      -0.005
==============================================================================
Omnibus:                       29.900   Durbin-Watson:                   2.347
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               60.190
Skew:                           1.422   Prob(JB):                     8.51e-14
Kurtosis:                       6.382   Cond. No.                     3.00e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

It turns out that as weight of cars increase it decreases the mpg. (so in other words: weight increase gas consumption)

Notice the price is not statistically significant anymore once we control for weight.

## Another example of Linear regression(OLS) with 3 variables

So lets say we have a theory about cars being made outside of the US are less likely consume a lot of gas. Gas is cheaper in the US so maybe car manifectures do not care about gas consumption too much compared to other countries (made up theory :))

so

we add one more variable in our model then: car being foreign or domestic made. We want to control for that as well.

In [19]:
df

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic
...,...,...,...,...,...,...,...,...,...,...,...,...
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,Foreign
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,Foreign
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,Foreign
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,Foreign
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,Foreign

In [20]:
df['foreign']

0     Domestic
1     Domestic
2     Domestic
3     Domestic
4     Domestic
        ...
69     Foreign
70     Foreign
71     Foreign
72     Foreign
73     Foreign
Name: foreign, Length: 74, dtype: category
Categories (2, object): ['Domestic' < 'Foreign']

So `foreign` variable if a categorical variable. Statistical models work with numbers. We have to translate this text(car being domestic or foreign made) into some numeric representation such as 0 or 1.

We could assign 1 if the car is foreign and 0 if the car is domestic.

That would help us to turn on/turn off the effect of being say foreign car.

In pandas, there is a function called `get_dummies`. So we will use that first to change the variable for our analysis. I will show two other methods as well below.

In [21]:
df.head()

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic

In [22]:
# Perform one-hot encoding on the 'foreign' column
pd.get_dummies(df, columns=['foreign'])

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign_Domestic,foreign_Foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,1,0
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,1,0
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,1,0
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,1,0
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,0,1
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,0,1
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,0,1
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,0,1
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,0,1

We need to be able to compare domestic car with foreign car. For that we have to exclude one category. **We cannot have both categories in our model** because it does not make sense. We need a comparison case category. This variable is not numeric in reality. it is a category, so we compare. It is not like one unit increase in being domestic car etc increase/decrease some degree in the dependent variable... So we have to exlude one category in our model.

`drop_first=True` does that trick for us.

In [23]:
# Perform one-hot encoding on the 'foreign' column
df = pd.get_dummies(df, columns=['foreign'], drop_first=True)

# Output the preprocessed DataFrame
df

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign_Foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,0
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,0
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,0
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,0
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,1
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,1
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,1
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,1
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,1

Now we do not have domestic category. But we know that if `foreign_Foreign` is 0 then that means it is `domestic`.

Now, we are ready to do our model fitting.

In `Pandas` if you want to retain the dataframe, you would use double brackets. This is also a way to subset several variables together as a dataframe.

In [24]:
#this is a Series. No longer a dataframe
df['mpg']

0     22
1     17
2     22
3     20
4     15
      ..
69    23
70    41
71    25
72    25
73    17
Name: mpg, Length: 74, dtype: int16

In [25]:
# This is a still a dataframe
df[['mpg']]

    mpg
0    22
1    17
2    22
3    20
4    15
..  ...
69   23
70   41
71   25
72   25
73   17

[74 rows x 1 columns]

In [26]:
y=df['mpg']
x= df[['price', 'weight', 'foreign_Foreign']]

x1=sm.add_constant(x)

x1

    const  price  weight  foreign_Foreign
0     1.0   4099    2930                0
1     1.0   4749    3350                0
2     1.0   3799    2640                0
3     1.0   4816    3250                0
4     1.0   7827    4080                0
..    ...    ...     ...              ...
69    1.0   7140    2160                1
70    1.0   5397    2040                1
71    1.0   4697    1930                1
72    1.0   6850    1990                1
73    1.0  11995    3170                1

[74 rows x 4 columns]

In [27]:
model= sm.OLS(y, x1).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.663
Model:                            OLS   Adj. R-squared:                  0.649
Method:                 Least Squares   F-statistic:                     45.93
Date:                Sat, 29 Jul 2023   Prob (F-statistic):           1.60e-16
Time:                        22:36:55   Log-Likelihood:                -194.14
No. Observations:                  74   AIC:                             396.3
Df Residuals:                      70   BIC:                             405.5
Df Model:                           3
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              41.9595      2.378     17.647      0.000      37.217      46.702
price             5.66e-05      0.000      0.294      0.769      -0.000       0.000
weight             -0.0068      0.001     -7.489      0.000      -0.009      -0.005
foreign_Foreign    -1.8559      1.289     -1.440      0.154      -4.427       0.715
==============================================================================
Omnibus:                       37.747   Durbin-Watson:                   2.432
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.111
Skew:                           1.720   Prob(JB):                     9.96e-21
Kurtosis:                       7.247   Cond. No.                     4.81e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.81e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Being a foreign car decreases the mpg compared to domestic cars but it is not statistically significant. However, weight is still significant.

So you now know how to use `statsmodels` for OLS regression. Check for more info on functions, parameters on statsmodels's website.

In [28]:
df

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign_Foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,0
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,0
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,0
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,0
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,0
...,...,...,...,...,...,...,...,...,...,...,...,...
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,1
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,1
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,1
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,1
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,1

# Logistic regression

lets say your dependent variable is a category of two. Something either exist or does not.

You may be from NY state or not.
You will buy a new car or not.

People who like hiking are more likely to live in NY compared to non-NY states. (Again, made up)

So any time your answer is yes/no or binary, then we are talking about logistic regression.

In [29]:
#lets get the original data once again

df=sm.datasets.webuse('auto')

df.tail(15)

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
59,Fiat Strada,4296,21,3.0,2.5,16,2130,161,36,105,3.37,Foreign
60,Honda Accord,5799,25,5.0,3.0,10,2240,172,36,107,3.05,Foreign
61,Honda Civic,4499,28,4.0,2.5,5,1760,149,34,91,3.30,Foreign
62,Mazda GLC,3995,30,4.0,3.5,11,1980,154,33,86,3.73,Foreign
63,Peugeot 604,12990,14,NaN,3.5,14,3420,192,38,163,3.58,Foreign
64,Renault Le Car,3895,26,3.0,3.0,10,1830,142,34,79,3.72,Foreign
65,Subaru,3798,35,5.0,2.5,11,2050,164,36,97,3.81,Foreign
66,Toyota Celica,5899,18,5.0,2.5,14,2410,174,36,134,3.06,Foreign
67,Toyota Corolla,3748,31,5.0,3.0,9,2200,165,35,97,3.21,Foreign
68,Toyota Corona,5719,18,5.0,2.0,11,2670,175,36,134,3.05,Foreign
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,Foreign
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,Foreign
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,Foreign
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,Foreign
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,Foreign

So we could use `lambda` to do the transformation about `foreign` variable.

In [30]:
#pd.get_dummies was first method. Here two more methods:

#second method
# Preprocess the 'Origin' column using map() and lambda function
df['Car_Origin'] = df['foreign'].map(lambda x: 1 if x == 'Foreign' else 0)

#third method
dictionary={"Foreign":1, "Domestic": 0}
df['Car_Origin2'] = df['foreign'].map(dictionary)

df

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign,Car_Origin,Car_Origin2
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic,0,0
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic,0,0
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic,0,0
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic,0,0
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,VW Dasher,7140,23,4.0,2.5,12,2160,172,36,97,3.74,Foreign,1,1
70,VW Diesel,5397,41,5.0,3.0,15,2040,155,35,90,3.78,Foreign,1,1
71,VW Rabbit,4697,25,4.0,3.0,15,1930,155,35,89,3.78,Foreign,1,1
72,VW Scirocco,6850,25,4.0,2.0,16,1990,156,36,97,3.78,Foreign,1,1
73,Volvo 260,11995,17,5.0,2.5,14,3170,193,37,163,2.98,Foreign,1,1

## Building the logistic regression model

Lets say we are interested in comparing domestic and foreign cars in terms of their price, mpg, weight etc.

Lets say our hypothesis is US-made cars are more heavier than foreign cars.

In [31]:
y= df['Car_Origin']
y

0     0
1     0
2     0
3     0
4     0
     ..
69    1
70    1
71    1
72    1
73    1
Name: Car_Origin, Length: 74, dtype: category
Categories (2, int64): [0 < 1]

In [32]:

x= df[['price', 'weight', 'mpg']]

x1=sm.add_constant(x)

x1

    const  price  weight  mpg
0     1.0   4099    2930   22
1     1.0   4749    3350   17
2     1.0   3799    2640   22
3     1.0   4816    3250   20
4     1.0   7827    4080   15
..    ...    ...     ...  ...
69    1.0   7140    2160   23
70    1.0   5397    2040   41
71    1.0   4697    1930   25
72    1.0   6850    1990   25
73    1.0  11995    3170   17

[74 rows x 4 columns]

In [33]:
model= sm.Logit(y, x1).fit()

print(model.summary())

Optimization terminated successfully.
         Current function value: 0.231917
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:             Car_Origin   No. Observations:                   74
Model:                          Logit   Df Residuals:                       70
Method:                           MLE   Df Model:                            3
Date:                Sat, 29 Jul 2023   Pseudo R-squ.:                  0.6189
Time:                        22:36:55   Log-Likelihood:                -17.162
converged:                       True   LL-Null:                       -45.033
Covariance Type:            nonrobust   LLR p-value:                 4.767e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         14.4224      5.414      2.664      0.008       3.810      25.034
price          0.0009      0.000      3.014      0.003       0.000       0.002
weight        -0.0068      0.002     -3.426      0.001      -0.011      -0.003
mpg           -0.1211      0.096     -1.266      0.206      -0.309       0.066
==============================================================================

Foreign cars are more likely to be expensive.

Foreign cars are less likely to be heavier.

Foreing cars are less likely to have higher mpg. (not significant)

## **The End**